"""Photo-guided, editable artifact meshes. Metres; not photogrammetry or CT.
Photographs are UV projected only where observed. See research/fidelity-sources.json.
"""
import math, random
from pathlib import Path
import bpy
import numpy as np
from mathutils import Vector

ROOT=Path(__file__).resolve().parents[1]
TAU=math.tau

def linear(c):
    v=np.array([int(c[i:i+2],16)/255 for i in (1,3,5)])
    return np.where(v<=.04045,v/12.92,((v+.055)/1.055)**2.4)

def mat(name,color,metal=0,rough=.5):
    m=bpy.data.materials.new(name);m.use_nodes=True
    p=m.node_tree.nodes.get('Principled BSDF');p.inputs['Base Color'].default_value=(*linear(color),1)
    p.inputs['Metallic'].default_value=metal;p.inputs['Roughness'].default_value=rough
    m.diffuse_color=(*linear(color),1)
    return m

def image_material(name,file,metal=0,rough=.5,maxsize=4096):
    m=mat(name,'#ffffff',metal,rough)
    im=bpy.data.images.load(str(ROOT/'research'/file),check_existing=True)
    if max(im.size)>maxsize:
        f=maxsize/max(im.size);im.scale(round(im.size[0]*f),round(im.size[1]*f))
    im.pack();im.colorspace_settings.name='sRGB'
    tex=m.node_tree.nodes.new('ShaderNodeTexImage');tex.image=im;tex.extension='EXTEND'
    m.node_tree.links.new(tex.outputs['Color'],m.node_tree.nodes['Principled BSDF'].inputs['Base Color'])
    m['texture_method']='registered photograph projection; lighting and perspective remain in the photo'
    return m

def aged(name,base,metal=.4,rough=.65):
    """A restrained, explicitly procedural surface study, with exported PBR maps."""
    m=mat(name,base,metal,rough);n=512
    rng=np.random.default_rng(39);v=np.zeros((n,n),dtype=np.float32)
    # Periodic interpolated random fields give granular patina without artificial stripes.
    yy,xx=np.mgrid[0:n,0:n]/n
    for grid,amp in [(7,.13),(23,.08),(67,.055),(191,.025)]:
        values=rng.normal(0,1,(grid,grid))
        x=xx*grid;y=yy*grid;ix=x.astype(int);iy=y.astype(int)
        tx=x-ix;ty=y-iy;tx=tx*tx*(3-2*tx);ty=ty*ty*(3-2*ty)
        v+=amp*((1-tx)*(1-ty)*values[iy%grid,ix%grid]+tx*(1-ty)*values[iy%grid,(ix+1)%grid]+(1-tx)*ty*values[(iy+1)%grid,ix%grid]+tx*ty*values[(iy+1)%grid,(ix+1)%grid])
    v+=rng.normal(0,.026,(n,n))
    colour=np.clip(linear(base)[None,None,:]*(1+v[:,:,None]*1.4),.001,1)
    def generated(label,values,space):
        im=bpy.data.images.new(name+'_'+label,width=n,height=n,alpha=False)
        im.colorspace_settings.name=space
        data=np.ones((n,n,4),dtype=np.float32);data[:,:,:3]=values
        im.pixels.foreach_set(data.ravel());im.pack()
        t=m.node_tree.nodes.new('ShaderNodeTexImage');t.image=im;return t
    # Generated byte images store encoded values; scene-linear values here would
    # be decoded a second time by the sRGB image texture and darken the material.
    encoded=np.where(colour<=.0031308,colour*12.92,1.055*colour**(1/2.4)-.055)
    albedo=generated('Albedo',encoded,'sRGB')
    r=generated('Roughness',np.repeat(np.clip(rough+v*.35,.2,.95)[:,:,None],3,2),'Non-Color')
    dx=(np.roll(v,1,1)-np.roll(v,-1,1))*.8;dy=(np.roll(v,1,0)-np.roll(v,-1,0))*.8
    normals=np.stack([dx,dy,np.ones_like(v)],axis=2);normals/=np.linalg.norm(normals,axis=2,keepdims=True)
    t=generated('Normal',normals*.5+.5,'Non-Color')
    normal=m.node_tree.nodes.new('ShaderNodeNormalMap');normal.inputs['Strength'].default_value=.35
    ls=m.node_tree.links;p=m.node_tree.nodes['Principled BSDF']
    ls.new(albedo.outputs['Color'],p.inputs['Base Color']);ls.new(r.outputs['Color'],p.inputs['Roughness'])
    ls.new(t.outputs['Color'],normal.inputs['Color']);ls.new(normal.outputs[0],p.inputs['Normal'])
    m['surface_accuracy']='procedural micro-surface, not recovered corrosion or scan data'
    m['albedo_encoding']='srgb-byte-v1'
    return m

class Builder:
    def __init__(self,c):self.c=c;self.objects=[]
    def add(self,o,name,m):
        o.name=name
        for c in list(o.users_collection):c.objects.unlink(o)
        self.c.objects.link(o)
        if m:o.data.materials.append(m)
        self.objects.append(o)
        return o
    def mesh(self,name,v,f,m,smooth=True):
        d=bpy.data.meshes.new(name);d.from_pydata(v,[],f);d.update()
        o=bpy.data.objects.new(name,d);self.add(o,name,m)
        for p in d.polygons:p.use_smooth=smooth
        self.uv(o,lambda v:(v.x*12,v.z*12+v.y*7))
        return o
    def uv(self,o,fn):
        layer=o.data.uv_layers.active or o.data.uv_layers.new(name='ArtifactUV')
        layer.name='ArtifactUV'
        for p in o.data.polygons:
            for li in p.loop_indices:layer.data[li].uv=fn(o.data.vertices[o.data.loops[li].vertex_index].co)
    def ellipsoid(self,name,loc,scale,m,segments=32,rings=16):
        bpy.ops.mesh.primitive_uv_sphere_add(segments=segments,ring_count=rings,location=loc)
        o=self.add(bpy.context.object,name,m);o.scale=scale
        bpy.ops.object.transform_apply(location=False,rotation=False,scale=True)
        for p in o.data.polygons:p.use_smooth=True
        return o
    def box(self,name,loc,size,m,bevel):
        bpy.ops.mesh.primitive_cube_add(size=1,location=loc);o=self.add(bpy.context.object,name,m);o.dimensions=size
        bpy.ops.object.transform_apply(location=False,rotation=False,scale=True)
        mod=o.modifiers.new('Rounded cut edges','BEVEL');mod.width=bevel;mod.segments=3
        return o
    def tube(self,name,pts,r,m,sides=10):
        points=[Vector(p) for p in pts];verts=[];faces=[]
        for i,p in enumerate(points):
            tangent=(points[min(i+1,len(points)-1)]-points[max(i-1,0)]).normalized()
            seed=Vector((0,1,0)) if abs(tangent.y)<.9 else Vector((1,0,0))
            u=tangent.cross(seed).normalized();w=tangent.cross(u).normalized()
            rr=r[i] if isinstance(r,list) else r
            rx,ry=rr if isinstance(rr,tuple) else (rr,rr)
            for k in range(sides):verts.append(tuple(p+u*math.cos(k*TAU/sides)*rx+w*math.sin(k*TAU/sides)*ry))
        for j in range(len(points)-1):
            for k in range(sides):faces.append((j*sides+k,j*sides+(k+1)%sides,(j+1)*sides+(k+1)%sides,(j+1)*sides+k))
        faces+=[tuple(reversed(range(sides))),tuple((len(points)-1)*sides+k for k in range(sides))]
        return self.mesh(name,verts,faces,m)
    def lathe(self,name,profile,m,segments=128):
        vs=[(r*math.cos(i*TAU/segments),r*math.sin(i*TAU/segments),z) for r,z in profile for i in range(segments)]
        fs=[(j*segments+i,j*segments+(i+1)%segments,(j+1)*segments+(i+1)%segments,(j+1)*segments+i) for j in range(len(profile)-1) for i in range(segments)]
        o=self.mesh(name,vs,fs,m)
        self.uv(o,lambda v:(math.atan2(v.y,v.x)/TAU+.5,v.z*5))
        return o
    def polygon(self,name,xz,depth,m,bevel=.003,y=0):
        # Explicit silhouette with rounded solid sidewalls, never a billboard.
        if sum(xz[i][0]*xz[(i+1)%len(xz)][1]-xz[(i+1)%len(xz)][0]*xz[i][1] for i in range(len(xz)))<0:xz=list(reversed(xz))
        v=[(x,y-d/2,z) for d in [depth,-depth] for x,z in xz];n=len(xz)
        fs=[tuple(range(n)),tuple(reversed(range(n,n*2)))]+[(i,(i+1)%n,(i+1)%n+n,i+n) for i in range(n)]
        o=self.mesh(name,v,fs,m,False)
        mod=o.modifiers.new('Carved silhouette edge','BEVEL');mod.width=bevel;mod.segments=4
        mod=o.modifiers.new('Carved face normals','WEIGHTED_NORMAL');mod.keep_sharp=True
        return o

def interpolate(points,steps=6):
    # Catmull-Rom sampling for continuous carved necks, tails and ornamental scrolls.
    ps=[np.array(p,float) for p in points];out=[]
    for i in range(len(ps)-1):
        p0,p1,p2,p3=ps[max(0,i-1)],ps[i],ps[i+1],ps[min(len(ps)-1,i+2)]
        for j in range(steps):
            t=j/steps
            out.append(tuple(.5*((2*p1)+(-p0+p2)*t+(2*p0-5*p1+4*p2-p3)*t*t+(-p0+3*p1-3*p2+p3)*t*t*t)))
    return out+[tuple(ps[-1])]

def sword(b):
    bronze=aged('剑身灰金青铜微表面','#a3915f',.72,.4)
    dark=aged('剑茎深褐青铜','#302e23',.6,.48)
    edge=mat('剑刃冷灰金属','#b3aa82',.82,.3)
    photo=image_material('实拍剑身_含鸟篆铭文','sword-whole-hd.jpg',.5,.44)
    # Use the measured total length; blade length is estimated from the whole photo.
    sections=[(0,.00003),(.009,.004),(.024,.010),(.052,.017),(.10,.022),(.17,.024),(.27,.025),(.36,.0245),(.446,.024)]
    vs=[]
    for z,w in sections:
        for x,y in [(-w,0),(-w*.85,-.0012),(0,-.0033),(.85*w,-.0012),(w,0),(.85*w,.0012),(0,.0033),(-.85*w,.0012)]:vs.append((x,y,z))
    fs=[(j*8+i,j*8+(i+1)%8,(j+1)*8+(i+1)%8,(j+1)*8+i) for j in range(len(sections)-1) for i in range(8)]
    o=b.mesh('剑身_连续收尖_中脊与薄刃',vs,fs,bronze,False);o.data.materials.append(photo);o.data.materials.append(edge)
    # Whole-photo blade spans x=798..3574; width bounds vary down its length.
    # Front is -Y. Photograph remains a photographed surface, not an inferred inscription.
    uv=o.data.uv_layers.active
    for face in o.data.polygons:
        face.material_index=1 if face.center.y<0 and abs(face.normal.y)>.4 else 0
        for li in face.loop_indices:
            v=o.data.vertices[o.data.loops[li].vertex_index].co
            t=v.z/.446;px=3574-t*2776;cy=520-17*t
            py=cy+v.x/.025*(58+16*t)
            uv.data[li].uv=(px/3722,1-py/780)
    # Curved wing-shaped guard replaces the old rectangular block.
    outline=[(-.029,.443),(-.028,.451),(-.018,.456),(-.008,.461),(0,.470),(.008,.461),(.018,.456),(.028,.451),(.029,.443),(.023,.439),(.010,.441),(0,.448),(-.010,.441),(-.023,.439)]
    b.polygon('剑格_双翼曲面',outline,.014,dark,.001)
    inlay=mat('剑格蓝色琉璃','#397886',.12,.22);turq=mat('剑格背面绿松石','#4e897c',.1,.7)
    for side in [-1,1]:
        for y,m in [(-.0075,inlay),(.0075,turq)]:
            b.ellipsoid('剑格嵌饰', (side*.019,y,.448),(.0045,.001,.0034),m)
        pts=interpolate([(side*.025,-.008,.444),(side*.020,-.008,.442),(side*.011,-.008,.446),(side*.007,-.008,.456)])
        b.tube('剑格细嵌槽',pts,.0005,edge,6)
    b.lathe('剑茎_收腰',[(.0075,.457),(.0074,.471),(.0066,.50),(.0078,.533),(.011,.539)],dark,96)
    for z in [.480,.506]:
        b.lathe('剑茎环箍',[(.0071,z),(.0079,z+.0007),(.0079,z+.0018),(.0071,z+.0023)],bronze,96)
    b.lathe('外翻卷圆盘剑首',[(.010,.535),(.016,.540),(.023,.545),(.024,.551),(.023,.554),(.020,.556),(.016,.553),(.007,.548),(0,.548)],dark,128)
    for i in range(11):
        r=.002+i*.0017;z=.549+(r/.020)**2*.004
        b.tube('剑首十一道同心圆',[(r*math.cos(t),r*math.sin(t),z) for t in np.linspace(0,TAU,97)],.00014,bronze,6)

def vase(b):
    glaze=mat('梅瓶内壁青白釉','#d6d2bc',0,.25)
    # Smooth profile registered to the front photo; height/neck/foot from museum data.
    knots=[(.065,0),(.065,.005),(.063,.013),(.063,.030),(.064,.06),(.069,.10),(.079,.16),(.092,.23),(.099,.28),(.100,.30),(.096,.32),(.087,.337),(.072,.349),(.050,.358),(.029,.362),(.027,.367),(.027,.376),(.032,.383),(.032,.387)]
    profile=interpolate(knots,5)+[(.027,.387),(.025,.379),(.024,.367),(.022,.36),(0,.358)]
    o=b.lathe('四爱梅瓶_丰肩短颈_圈足_中空瓶口',profile,glaze,192)
    # Four observed story panels. Their circumferential registration is approximate.
    # Coordinate measurements refer to 1280x1920 previews of the unmodified originals.
    photos=[('front',630,162,1789,406),('wang',606,270,1788,414),('tao',580,237,1738,402),('zhou',638,392,1574,322)]
    # Bake the four calibrated projections into one cylindrical UV atlas. Smooth
    # angular weights avoid hard material boundaries; this is photographic
    # registration, not a recovered seamless scan texture.
    w,h=4096,2048
    angles=np.arange(w,dtype=np.float32)/w*TAU
    zs=np.arange(h,dtype=np.float32)/(h-1)*.387
    radius=np.interp(zs,[p[1] for p in knots],[p[0] for p in knots])
    atlas=np.zeros((h,w,3),np.float32);total=np.zeros((1,w,1),np.float32)
    reference_white=None;front_foot=None
    for q,(slug,cx,top,bottom,half) in enumerate(photos):
        im=bpy.data.images.load(str(ROOT/'research'/('vase-'+slug+'-hd.jpg')),check_existing=True)
        f=min(1,4096/max(im.size));im.scale(round(im.size[0]*f),round(im.size[1]*f))
        iw,ih=im.size;buf=np.empty(iw*ih*4,np.float32);im.pixels.foreach_get(buf)
        pixels=buf.reshape(ih,iw,4)[:,:,:3]
        delta=(angles-q*math.pi/2+math.pi)%TAU-math.pi
        sx=radius[:,None]*np.sin(delta)[None,:]
        px=np.clip((cx+sx/.1*half)/1280*(iw-1),0,iw-1)
        py=np.clip((1-(bottom-zs/.387*(bottom-top))/1920)*(ih-1),0,ih-1)
        x0=px.astype(int);x1=np.minimum(x0+1,iw-1);y0=py.astype(int);y1=np.minimum(y0+1,ih-1)
        tx=(px-x0)[:,:,None];ty=(py-y0)[:,None,None]
        colour=(pixels[y0[:,None],x0]*(1-tx)+pixels[y0[:,None],x1]*tx)*(1-ty)+(pixels[y1[:,None],x0]*(1-tx)+pixels[y1[:,None],x1]*tx)*ty
        # Calibrate photographed illumination from bright glaze within each view.
        # A single row gain preserves blue hues and actual brushwork.
        center_band=np.abs(delta)<.4
        luminance=colour[:,center_band,:]@np.array([.2126,.7152,.0722])
        white=np.quantile(luminance,.88,axis=1)
        white=np.convolve(np.pad(white,(20,20),mode='edge'),np.ones(41)/41,mode='valid')
        if q==0:reference_white=white;front_foot=colour.copy()
        else:colour*=np.clip(reference_white/np.maximum(white,.01),.55,2.5)[:,None,None]
        # Avoid supports visible at the outside edges of the older photographs.
        if q:
            foot_mix=np.clip((.10-zs)/.04,0,1)[:,None,None]
            colour=colour*(1-foot_mix)+np.roll(front_foot,q*w//4,axis=1)*foot_mix
        weight=np.clip((math.pi/4+.13-np.abs(delta))/.26,0,1)
        weight=weight*weight*(3-2*weight)
        atlas+=colour*weight[None,:,None];total+=weight[None,:,None]
    atlas=np.clip(atlas/np.maximum(total,.001),0,1)
    packed=bpy.data.images.new('四爱四面照片_曝光校准与接缝混合',width=w,height=h,alpha=False)
    packed.colorspace_settings.name='sRGB'
    rgba=np.ones((h,w,4),np.float32);rgba[:,:,:3]=atlas
    packed.pixels.foreach_set(rgba.ravel());packed.pack()
    m=mat('四爱梅瓶_四面实拍环向贴图','#ffffff',0,.34)
    tex=m.node_tree.nodes.new('ShaderNodeTexImage');tex.image=packed
    m.node_tree.links.new(tex.outputs['Color'],m.node_tree.nodes['Principled BSDF'].inputs['Base Color'])
    m.node_tree.nodes['Principled BSDF'].inputs['Coat Weight'].default_value=.12
    m['texture_method']='Four photographs reprojected; row exposure calibrated; angular seams blended. CC BY-SA 4.0; see fidelity-sources.json.'
    o.data.materials.append(m)
    uv=o.data.uv_layers.active
    for face in o.data.polygons:
        if face.index//192>=len(profile)-5:continue
        face.material_index=1
        center=(math.atan2(face.center.y,face.center.x)+math.pi/2)%TAU
        for li in face.loop_indices:
            v=o.data.vertices[o.data.loops[li].vertex_index].co
            angle=(math.atan2(v.y,v.x)+math.pi/2)%TAU
            if angle-center>math.pi:angle-=TAU
            if center-angle>math.pi:angle+=TAU
            uv.data[li].uv=(angle/TAU,v.z/.387)

def zun(b):
    bronze=aged('尊盘暗褐青铜_不均匀氧化层','#635843',.48,.63)
    relief=aged('尊盘凸起纹饰磨蚀面','#73664e',.42,.67)
    recessed=mat('尊盘凹部','#39372e',.18,.8)
    # Pan's body is shallow and nearly vertical, with feet, handles and a dense crown.
    pan=[(0,.040),(.180,.040),(.211,.051),(.238,.081),(.253,.124),(.257,.170),(.261,.189),(.290,.190),(.290,.199),(.255,.199),(.249,.168),(.242,.105),(.215,.067),(0,.067)]
    b.lathe('盘_浅腹折沿_内腔',interpolate(pan,3),bronze,144)
    # Zun itself is 30.1 cm; seated on the inner bottom of the pan.
    base=.067
    profile=[(.067,base),(.071,base+.008),(.067,base+.034),(.055,base+.056),(.058,base+.078),(.080,base+.105),(.082,base+.128),(.070,base+.153),(.056,base+.19),(.057,base+.231),(.069,base+.254),(.105,base+.275),(.113,base+.281),(.106,base+.284),(.092,base+.276),(.054,base+.250),(.050,base+.195)]
    b.lathe('尊_圈足鼓腹_细长颈_敞口',interpolate(profile,4),bronze,144)
    # Dense interwoven openwork occupying the measured 25cm and 58cm mouth diameters.
    # Motif topology is reconstructed from photos, not the inaccessible CT model.
    def crown(radius,width,z,rows,count,tube_r):
        for row in range(rows):
            for i in range(count):
                a=TAU*(i+row*.618)/count
                pts=[]
                for t in np.linspace(0,TAU*1.7,28):
                    rr=radius-width*.5+width*row/max(1,rows-1)+math.cos(t)*width*.20
                    aa=a+math.sin(t)*TAU/count*.53
                    pts.append((rr*math.cos(aa),rr*math.sin(aa),z+math.sin(row*2.4)*.003+math.sin(t*2)*tube_r*2.3))
                b.tube('多层蟠虺透空附饰',pts,tube_r,relief,6)
        for i in range(count):
            a=i*TAU/count;rr=radius+width*.47
            pts=[(rr*math.cos(a+.009*math.sin(t)),rr*math.sin(a+.009*math.sin(t)),z-.014+t/TAU*.014) for t in np.linspace(0,TAU,20)]
            b.tube('口沿外层盘曲龙蛇',pts,tube_r*1.15,bronze,6)
    crown(.110,.028,.354,7,88,.0013)
    crown(.110,.028,.362,6,83,.00125)
    crown(.272,.033,.202,6,161,.0011)
    crown(.272,.032,.209,4,157,.0010)
    def radial(a,x,y,z):return (math.cos(a)*x-math.sin(a)*y,math.sin(a)*x+math.cos(a)*y,z)
    def scroll(a,r,z,w,h,m):
        pts=[]
        for t in np.linspace(0,TAU*1.55,40):
            k=1-t/(TAU*1.95)
            pts.append(radial(a,r+.001*math.sin(t*3),w*k*math.cos(t),z+h*k*math.sin(t)))
        b.tube('蟠螭卷曲浮雕',pts,.0018,m,7)
    for radius,z,count in [(.080,.174,28),(.066,.107,26),(.061,.253,38),(.253,.138,100)]:
        for i in range(count):scroll(TAU*i/count,radius,z,.008,.012,relief)
    for z,r in [(.093,.243),(.157,.256),(.184,.260)]:
        b.tube('盘腹弦纹',[(r*math.cos(a),r*math.sin(a),z) for a in np.linspace(0,TAU,241)],.0012,relief,8)
    for radius,z,count in [(.076,.177,48),(.075,.197,48),(.062,.277,55),(.061,.296,55),(.253,.117,130),(.257,.146,130)]:
        for i in range(count):scroll(TAU*(i+.36)/count,radius,z,.0045,.006,relief)
    # Four handles and four independently modelled crouching/curled supports.
    for i in range(4):
        a=TAU*i/4+math.pi/4
        for k in range(3):
            rr=.265+k*.012
            pts=[radial(a,rr,.047*math.cos(t),.220+.008*math.sin(t)) for t in np.linspace(0,TAU,45)]
            b.tube('盘四抠手透空骨架',pts,.0024,bronze,8)
        for k in range(18):
            y=(k%6-2.5)*.015;r=.263+(k//6)*.012
            pts=[radial(a,r+.006*math.cos(t),y+.009*math.sin(t),.225+.003*math.sin(3*t)) for t in np.linspace(0,TAU*1.5,28)]
            b.tube('抠手镂空盘蛇',pts,.001,relief,6)
        foot=[(0,.006),(-.009,.003),(-.020,.013),(-.015,.024),(-.028,.034),(-.022,.051),(-.026,.068),(-.018,.092),(-.017,.126),(-.010,.159),(.010,.163),(.023,.140),(.017,.111),(.026,.088),(.018,.065),(.028,.051),(.018,.033),(.016,.020),(.007,.014),(.015,.004)]
        plate=b.polygon('盘足_云纹兽形片状支承',foot,.010,bronze,.002)
        plate.rotation_euler.z=a-math.pi/2;plate.location=Vector(radial(a,.275,0,0))
        for z in [.03,.075,.113]:
            scroll(a,.283,z,.021,.019,relief)
            scroll(a+.036,.284,z+.012,.012,.012,relief)
        head=b.ellipsoid('盘足兽首',radial(a,.275,0,.164),(.021,.018,.022),bronze)
        head.rotation_euler.z=a
        for offset in [-.012,.012]:
            b.ellipsoid('兽首双目',radial(a,.292,offset,.173),(.005,.005,.004),relief,20,12)
            scroll(a+offset*3,.293,.155,.017,.02,relief)
        # Four climbing, backward-looking felines on the neck of the zun.
        p=interpolate([radial(a,.082,0,.20),radial(a,.095,0,.232),radial(a,.090,0,.274),radial(a,.102,0,.315),radial(a,.108,0,.335)])
        b.tube('尊颈四豹攀附躯体',p,.0058,bronze,12)
        head=b.ellipsoid('反首豹头',radial(a,.112,0,.333),(.01,.007,.007),bronze)
        head.rotation_euler.z=a
        b.tube('豹吐舌',interpolate([radial(a,.117,0,.331),radial(a,.125,0,.320),radial(a,.120,0,.316)]),.0013,relief,6)
        for z in [.225,.290]:
            for side in [-1,1]:b.tube('豹攀附四足',interpolate([radial(a,.092,0,z),radial(a,.101,side*.011,z-.01),radial(a,.073,side*.014,z-.018)]),.0026,bronze,8)

# Pixel coordinates below were traced against the museum's white-background
# catalogue photograph. They are shape evidence, not recovered object depth.
def drum(b):
    lacquer=aged('虎鼓黑漆_局部磨蚀','#24201c',.06,.49)
    red=aged('虎鼓朱红漆绘','#762b21',.02,.58)
    ochre=mat('虎鼓黄褐漆线','#aa8250',.03,.64)
    # The high-resolution exhibition photo has broad specular streaks and an
    # unverified drum membrane. Use the catalogue's documented dark lacquer
    # surface instead of baking its exhibition highlights into the model.
    front=mat('虎鼓馆方目录漆绘投影','#ffffff',.04,.64)
    source=bpy.data.images.load(str(ROOT/'research/tiger-drum-reference.jpg'),check_existing=True)
    iw,ih=source.size;pixels=np.empty(iw*ih*4,np.float32);source.pixels.foreach_get(pixels)
    pixels=pixels.reshape(ih,iw,4)
    # Outside the traced silhouette the catalogue is white; do not project the
    # white background onto approximate bevels and rounded, unobserved depth.
    background=(pixels[:,:,:3].min(axis=2)>.18)&(pixels[:,:,:3].max(axis=2)-pixels[:,:,:3].min(axis=2)<.20)
    pixels[background,:3]=linear('#24201c')
    teximg=bpy.data.images.new('虎鼓目录_排除白色背景',width=iw,height=ih,alpha=False)
    teximg.pixels.foreach_set(pixels.ravel());teximg.pack()
    tex=front.node_tree.nodes.new('ShaderNodeTexImage');tex.image=teximg;tex.extension='EXTEND'
    front.node_tree.links.new(tex.outputs['Color'],front.node_tree.nodes['Principled BSDF'].inputs['Base Color'])
    def projection(v):
        px=v.x/.00335+354;py=470-v.z/.0035763
        return (px/700,1-py/600)
    # Axes registered to catalogue extents, excluding the modern plinth and beaters.
    def xyz(p,y=0):return ((p[0]-354)*1.34/400,y,(470-p[1])*1.359/380)
    def silhouette(name,px,depth,bevel=.004):
        outline=[(xyz(p)[0],xyz(p)[2]) for p in px]
        outline=interpolate(outline+[outline[0]],3)[:-1]
        o=b.polygon(name,outline,depth,lacquer,bevel)
        o.data.materials.append(front)
        for f in o.data.polygons:
            if f.normal.y<-.5:f.material_index=1
        b.uv(o,projection)
        return o
    def stroke(name,ps,width,m=red,y=-.029):return b.tube(name,interpolate([xyz(p,y) for p in ps]),width,m,10)
    # Accurate long S-necks and broad horizontal wing bodies, instead of rods.
    left=[(345,293),(291,295),(245,300),(222,304),(218,283),(226,257),(238,227),(244,195),(243,170),(234,147),(223,136),(209,130),(205,153),(220,172),(227,195),(224,219),(213,245),(201,272),(194,299),(197,320),(210,338),(236,350),(270,343),(298,333),(323,321),(345,321)]
    head=[(229,138),(229,121),(220,112),(223,102),(213,98),(207,94),(196,97),(191,109),(186,112),(176,108),(157,107),(158,115),(178,119),(189,126),(195,139),(203,150),(216,149)]
    tiger=[(326,410),(322,397),(310,388),(292,386),(272,391),(258,400),(245,406),(236,397),(228,381),(214,369),(196,368),(189,374),(189,384),(199,388),(202,394),(191,397),(188,408),(197,414),(208,414),(213,432),(210,446),(181,447),(161,452),(155,461),(181,464),(218,459),(251,462),(277,463),(295,456),(316,448),(321,430)]
    for side in [-1,1]:
        mirror=lambda p:p if side<0 else (708-p[0],p[1])
        spine=[(334,307),(299,315),(264,324),(235,326),(213,308),(212,276),(226,239),(234,208),(234,181),(226,157),(213,139)]
        points=interpolate([xyz(mirror(p)) for p in spine],8)
        widths=[14,15,19,21,18,10,9,9,8,10,15]
        rr=[(float(np.interp(i/(len(points)-1),np.linspace(0,1,len(widths)),widths))*.00335,.043) for i in range(len(points))]
        body=b.tube('凤鸟_连续雕刻弧颈与翼部',points,rr,lacquer,24)
        body.data.materials.append(front)
        for f in body.data.polygons:
            if f.normal.y<-.15:f.material_index=1
        b.uv(body,projection)
        silhouette('凤鸟_张喙冠首',[mirror(p) for p in head],.070,.004)
        silhouette('卧虎_昂首屈伏躯体',[mirror(p) for p in tiger],.12,.018)
        # Actual rounded cheeks, haunches, folded paws and front/back relief.
        for px,pz,rx,rz in [(217,411,13,30),(293,415,28,27),(205,384,12,13)]:
            x,y,z=xyz(mirror((px,pz)),-.026)
            o=b.ellipsoid('虎体起伏雕刻',(x,y,z),(rx*.00335,.055,rz*.00355),lacquer)
            o.data.materials.append(front)
            for f in o.data.polygons:
                if f.normal.y<-.2:f.material_index=1
            b.uv(o,lambda v,o=o:projection(v+o.location))
        for y in [-.045,.045]:
            for ps in [[(296,407),(281,424),(271,447),(282,455),(300,454)],[(218,417),(221,441),(212,454),(191,455),(171,456)]]:
                stroke('虎屈伏足部',[mirror(p) for p in ps],.010,lacquer,y)
        stroke('卧虎上卷长尾',[mirror(p) for p in [(313,410),(334,394),(330,380),(305,373),(300,358),(310,351),(317,359),(311,365)]],.0085,lacquer,-.004)
        stroke('虎尾红漆描线',[mirror(p) for p in [(314,407),(330,394),(327,383),(305,377),(296,362),(304,352),(314,356)]],.0022,red,-.015)
        stroke('凤鸟长腿',[mirror(p) for p in [(249,342),(249,365),(247,393),(244,408)]],.011,red,0)
        for k in range(3):stroke('凤爪',[mirror(p) for p in [(244,407),(239+k*5,416),(236+k*6,420)]],.0028,lacquer,-.004)
        stroke('鸟翼下卷羽',[mirror(p) for p in [(335,314),(331,336),(321,351),(314,346),(316,338)]],.010,lacquer,0)
        for k in range(3):
            stroke('凤翼羽线',[mirror(p) for p in [(228,309+k*3),(248,303+k*3),(276,308+k*3),(304,313+k*3),(331,311+k*3)]],.0014,ochre,-.046)
        # The two small animals are distinct supports, not wing decorations.
        stroke('承鼓小兽躯干',[mirror(p) for p in [(253,294),(256,274),(270,260),(278,239)]],.014,lacquer,-.004)
        o=b.ellipsoid('承鼓小兽头',xyz(mirror((278,239))),(.016,.020,.016),lacquer)
        for ps in [[(260,277),(251,285),(250,296)],[(266,255),(285,251),(291,238)]]:stroke('小兽承托肢',[mirror(p) for p in ps],.006,lacquer)
        for k in range(6):
            p=mirror((196+k*4,104-k%2*3));q=mirror((197+k*4,116))
            stroke('凤冠刻棱',[p,q],.002,ochre,-.037)
        for p in [(203,122),(201,387),(294,414)]:
            x,y,z=xyz(mirror(p),-.065)
            b.ellipsoid('圆眼与关节',(x,y,z),(.009,.003,.009),lacquer,24,12)
            pts=[(x+.009*math.cos(a),y-.004,z+.009*math.sin(a)) for a in np.linspace(0,TAU,49)]
            b.tube('圆眼描边',pts,.001,ochre,6)
    # Preserve the broken, open frame from the museum catalogue photograph.
    # The 2021 exhibition photo has a membrane, but its restoration status is unknown.
    rng=random.Random(16);center=xyz((359,175));radius=.296
    for i in range(44):
        a=TAU*i/44
        if i in [3,6,11,17,27,38]:continue
        da=TAU/44*.84;points=[];rs=[]
        for t in np.linspace(a,a+da,6):
            points.append((center[0]+radius*math.cos(t),0,center[2]+radius*math.sin(t)));rs.append((.012+rng.random()*.015,.041))
        b.tube('缺损鼓腔_保留开口',points,rs,lacquer,12)
    b.tube('残鼓框内支撑',[(center[0]+radius*math.cos(t),.007,center[2]+radius*math.sin(t)) for t in np.linspace(0,TAU,193)],.004,lacquer,8)
    for i in range(10):
        a=TAU*i/10
        b.tube('残框漆饰',[(center[0]+(radius+.015)*math.cos(t),-.043,center[2]+(radius+.015)*math.sin(t)) for t in np.linspace(a,a+.11,9)],.0022,red,6)

def bamboo(b):
    wood=aged('竹简褐黄色纤维','#a48758',0,.82)
    ink=image_material('秦简馆方照片_实际五枚文字','bamboo-reference.jpg',0,.9,2048)
    # Five photographed slips replace the invented 34 identical bars and ropes.
    # UVs omit the modern number labels and clear storage sleeves.
    for i,(px,width) in enumerate([(302,8),(324,8),(344,8),(367,8),(385,8)]):
        center=(i-2)*.013;rng=random.Random(i+74)
        vs=[];faces=[];segments=64
        for j in range(segments+1):
            z=j/segments*.25
            x=center+math.sin(j/segments*math.pi*1.2+i)*.0005
            y=math.sin(j/segments*TAU+i)*.0008
            for dx,dy in [(-.0044,.0012),(-.0045,-.0008),(0,-.0017),(.0045,-.0008),(.0044,.0012)]:
                vs.append((x+dx+rng.uniform(-.00007,.00007),y+dy,z))
        for j in range(segments):
            for k in range(4):faces.append((j*5+k,(j+1)*5+k,(j+1)*5+k+1,j*5+k+1))
        o=b.mesh('秦简_实拍第'+str(i+1)+'枚',vs,[tuple(reversed(f)) for f in faces],wood)
        o.data.materials.append(ink)
        for f in o.data.polygons:f.material_index=1 if f.index%4 in [1,2] else 0
        b.uv(o,lambda v,px=px,center=center:((px+(v.x-center)/.0045*width)/700,1-(540-v.z/.25*470)/600))
    # Depth and 25 cm display scale are approximate; no invented reconstruction text.

BUILDERS={'sword':sword,'zun':zun,'drum':drum,'vase':vase,'bamboo':bamboo}

def build(slug,collection):
    b=Builder(collection);BUILDERS[slug](b)
    if slug=='drum':
        bpy.context.view_layer.update()
        pts=[o.matrix_world@Vector(v) for o in b.objects for v in o.bound_box]
        minz=min(p.z for p in pts);sx=1.34/(max(p.x for p in pts)-min(p.x for p in pts));sz=1.359/(max(p.z for p in pts)-minz)
        for o in b.objects:
            o.location.x*=sx;o.location.z=(o.location.z-minz)*sz;o.scale.x*=sx;o.scale.z*=sz
    for o in b.objects:
        o['artifact_id']=slug;o['part']='06_Artifacts_照片依据补建'
        o['accuracy']='photo_guided_reconstruction_not_scan; unknown depth and pattern topology remain approximate'
    for o in b.objects:
        if o.type=='MESH' and o.data.uv_layers.active:o.data.uv_layers.active.name='ArtifactUV'
    return b.objects
