"""Refine the existing museum spaces from the preserved 0.4 scene files.

Run with Blender: -- galleries | public | campus | assemble | gallery-id.
The 0.10 materials are photo-guided studies, not measured PBR or surveyed geometry.
Source files are read from the scoped before-space-polish-10 backup on each run.
"""
import sys, math, json, random, shutil
from pathlib import Path
import bpy
import numpy as np
from mathutils import Vector

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from artifact_geometry import Builder, mat, linear
from full_museum_spaces import text, beam, area, spot, luminous
from build_full_museum import GALLERIES, optimize_export, export_gallery, append_objects
from artifact_detail_geometry import refine
from repair_procedural_colour import repair

SOURCE = ROOT / 'backups/before-space-polish-10/models'
RENDERS = ROOT / 'renders/space-10'
RENDERS.mkdir(parents=True, exist_ok=True)
PALETTES = {
    'zeng': ('#334a40', '#736759', '#baaa88'),
    'sword-hall': ('#322a22', '#373635', '#c1b397'),
    'family': ('#49382b', '#494841', '#b7a27b'),
    'chu': ('#30221e', '#494139', '#bda889'),
    'liang': ('#cfc5b1', '#50473c', '#c5b590'),
    'music': ('#c1b196', '#554c3e', '#c9b78e'),
    'craft': ('#286566', '#39413f', '#aebbb4'),
    'ancient': ('#20392b', '#3e463d', '#c3ad82'),
    'ceramics': ('#bdab87', '#504c41', '#cfcaaf'),
    'modern': ('#374857', '#373d40', '#c0c1b7'),
    'people': ('#b9a887', '#5a493b', '#c8b593'),
}


def surface(name, color, kind='stone', rough=.6, metal=0):
    """Periodic direct albedo/roughness/normal maps supported by glTF."""
    m = mat('10_' + name, color, metal, rough)
    n = 512
    y, x = np.mgrid[0:n, 0:n] / n
    rng = np.random.default_rng(53)
    grain = rng.normal(0, 1, (n, n))
    broad = np.sin(2*math.pi*(x*3 + .19*np.sin(y*2*math.pi))) * np.cos(2*math.pi*y*4)
    fine = np.sin(2*math.pi*(x*19+y*13)) * .16 + grain * .14
    if kind == 'marble':
        phase = x*2 + y + .44*np.sin(y*2*math.pi) + .22*np.sin((x+y)*6*math.pi) + .08*np.sin(y*18*math.pi)
        veins = np.exp(-np.square(np.sin(phase*math.pi)/.07))
        variation = broad*.055 - veins*.11 + fine*.025
        height = veins*.018 + fine*.025
    elif kind == 'wood':
        growth = x*24 + .25*np.sin(y*2*math.pi) + .12*np.sin(x*8*math.pi)
        variation = np.sin(growth*2*math.pi)*.12 + np.sin(growth*6*math.pi)*.035 + grain*.025
        height = variation*.22
    elif kind == 'fabric':
        variation = (np.sin(x*n*math.pi/2)*np.sin(y*n*math.pi/2))*.07 + grain*.03
        height = variation*.3
    elif kind == 'water':
        variation = broad*.08 + fine*.016
        height = np.sin(2*math.pi*(x*11 + .12*np.sin(y*8*math.pi)))*.17 + np.sin(2*math.pi*(y*23+x*2))*.08
    elif kind == 'grass':
        variation = broad*.13 + fine*.18
        height = fine*.25
    else:
        variation = broad*.045 + fine*.045
        height = fine*.09
    rgb = np.clip(linear(color)[None,None,:]*(1+variation[:,:,None]), .0001, 1)
    def texture(label, values, space):
        im = bpy.data.images.new(m.name+'_'+label, width=n, height=n, alpha=False)
        im.colorspace_settings.name = space
        pixels = np.ones((n,n,4), dtype=np.float32)
        pixels[:,:,:3] = values
        im.pixels.foreach_set(pixels.ravel()); im.pack()
        node = m.node_tree.nodes.new('ShaderNodeTexImage'); node.image = im
        return node
    # Generated byte images store encoded channel values. Writing scene-linear
    # RGB to an sRGB byte image would decode twice and make dark paint almost black.
    encoded = np.where(rgb<=.0031308, rgb*12.92, 1.055*rgb**(1/2.4)-.055)
    albedo = texture('Albedo', encoded, 'sRGB')
    rmap = texture('Roughness', np.repeat(np.clip(rough+variation*.15,.06,1)[:,:,None],3,2), 'Non-Color')
    dx = (np.roll(height,1,1)-np.roll(height,-1,1))*2
    dy = (np.roll(height,1,0)-np.roll(height,-1,0))*2
    normal = np.stack([dx,dy,np.ones_like(dx)],axis=2)
    normal /= np.linalg.norm(normal,axis=2,keepdims=True)
    nmap = texture('Normal', normal*.5+.5, 'Non-Color')
    p = m.node_tree.nodes['Principled BSDF']; links = m.node_tree.links
    links.new(albedo.outputs['Color'],p.inputs['Base Color'])
    links.new(rmap.outputs['Color'],p.inputs['Roughness'])
    node = m.node_tree.nodes.new('ShaderNodeNormalMap'); node.inputs['Strength'].default_value=.4
    links.new(nmap.outputs['Color'],node.inputs['Color']); links.new(node.outputs[0],p.inputs['Normal'])
    m['reference_srgb'] = color
    m['surface_accuracy'] = 'photo-guided procedural '+kind+'; not a measured texture'
    m['space_revision'] = '0.10'
    return m


def project_uv(o, metres=2):
    if o.type != 'MESH': return
    uv = o.data.uv_layers.active or o.data.uv_layers.new(name='UVMap')
    uv.name = 'UVMap'
    for p in o.data.polygons:
        axis = max(range(3), key=lambda a: abs(p.normal[a]))
        a, b = [(1,2),(0,2),(0,1)][axis]
        for li in p.loop_indices:
            co = o.matrix_world @ o.data.vertices[o.data.loops[li].vertex_index].co
            uv.data[li].uv = (co[a]/metres, co[b]/metres)


def assign(o, material, metres=2):
    o.data.materials.clear(); o.data.materials.append(material)
    project_uv(o, metres)


def builder(s, name):
    c = bpy.data.collections.new('Polish10_'+name); s.collection.children.link(c)
    return Builder(c)


def finish(s, slug, path, render=True):
    s['procedural_colour_repairs']=json.dumps(repair(bpy.data.materials),ensure_ascii=False)
    # Area lights illuminate interiors without appearing as large white softboxes in glazing.
    for o in s.objects:
        if o.type=='LIGHT' and o.data.type=='AREA':o.data.specular_factor=0
    s['space_revision']='0.10'
    s['surface_accuracy']='photo-guided material studies; layout, hidden surfaces and lighting approximate'
    s.render.engine='CYCLES';s.cycles.samples=32;s.cycles.use_denoising=True
    s.render.resolution_x=1440;s.render.resolution_y=960;s.render.resolution_percentage=100
    s.render.image_settings.file_format='JPEG';s.render.image_settings.quality=94
    s.view_settings.view_transform='AgX';s.view_settings.look='AgX - Medium High Contrast'
    # Opening a .blend should expose materials, not the default uniform gray solid view.
    for screen in bpy.data.screens:
        for a in screen.areas:
            if a.type=='VIEW_3D':
                a.spaces.active.shading.type='MATERIAL'
                a.spaces.active.shading.use_scene_world=False
                a.spaces.active.shading.studiolight_rotate_z=.35
                if s.camera:
                    a.spaces.active.region_3d.view_perspective='CAMERA'
    s.render.filepath=str(RENDERS/(slug+'.jpg'))
    bpy.ops.outliner.orphans_purge(do_recursive=True)
    bpy.ops.wm.save_as_mainfile(filepath=str(path),compress=True)
    if render: bpy.ops.render.render(write_still=True)


def gallery(g):
    slug=g['id'];print('POLISH_GALLERY',slug,flush=True)
    bpy.ops.wm.open_mainfile(filepath=str(SOURCE/'galleries'/(slug+'.blend')),load_ui=False)
    s=bpy.context.scene;b=builder(s,slug)
    wallcolor,floorcolor,liningcolor=PALETTES[slug]
    wall=surface(slug+'展墙',wallcolor,'stone',.88)
    floor=surface(slug+'磨光石地坪',floorcolor,'marble',.32)
    lining=surface(slug+'展柜织物',liningcolor,'fabric',.96)
    trim=mat('10_展柜炭黑金属','#242722',.48,.3)
    brass=mat('10_展陈深古铜','#84704b',.55,.4)
    ink=mat('10_暖白字色','#e9debf',0,.7)
    darkink=mat('10_浅底文字','#514533',0,.8)
    for o in list(s.objects):
        if o.get('artifact_id'):continue
        if o.type=='MESH':
            if o.name.startswith(('后部展墙','侧展墙','入口侧墙','分段展墙')):assign(o,wall,3)
            elif o.name.startswith('分区地坪'):assign(o,floor,3.2)
            elif '衬台' in o.name:assign(o,lining,.6)
            elif '柜座' in o.name or '柜顶' in o.name:assign(o,trim)
            elif o.name.startswith(('地坪纵缝','地坪横缝')):
                assign(o,mat('10_细石缝','#353832',0,.8))
                o.scale.x *= .55 if o.name.startswith('地坪纵') else 1
                o.scale.y *= .55 if o.name.startswith('地坪横') else 1
            elif '可见顶棚格栅' in o.name and slug in ['ancient','music','people','craft']:
                assign(o,mat('10_吊顶格栅'+slug, '#625c45' if slug in ['ancient','music'] else '#72746a',.3,.6))
        if o.type=='FONT' and o.location.z>3:
            assign(o,darkink if slug in ['liang','music','ceramics','people'] else ink)
        if o.type=='LIGHT':
            if o.data.type=='AREA':
                o.data.energy*=.55;o.data.specular_factor=.15
            elif o.data.type=='SPOT':
                o.data.energy*=.75;o.data.color=(1,.84,.64)
                o['web_intensity']=46.0 if '展品照明' in o.name else 16.0
                o['web_shadow']='展品照明' in o.name
    # Match the current refined static shape without adding interaction tools/cameras to a gallery.
    for item in g['artifacts']:
        if item['id'] in ['drum-chongyang','vase','manuscript-xiong']:
            old=[o for o in s.objects if o.get('artifact_id')==item['id']]
            # Refiner uses source names and coordinates: refine a loaded library in a temporary scene,
            # then link only its meshes at the known display offset.
            for o in old:bpy.data.objects.remove(o,do_unlink=True)
            temp=bpy.data.scenes.new('RefinedArtifactTemporary');bpy.context.window.scene=temp
            c=bpy.data.collections.new('RefinedStatic_'+item['id']);temp.collection.children.link(c)
            append_objects(ROOT/'models/artifacts'/(item['id']+'.blend'),c)
            refine(item['id'])
            for o in list(temp.objects):
                if o.type not in ['MESH','CURVE','FONT']:
                    bpy.data.objects.remove(o,do_unlink=True);continue
                for collection in list(o.users_collection):collection.objects.unlink(o)
                b.c.objects.link(o)
                if not o.parent:o.location+=Vector((item['x'],item['y'],item['base']+.045))
                o['artifact_id']=item['id'];o['gallery_id']=slug
            bpy.context.window.scene=s;bpy.data.scenes.remove(temp)
    # Case edges, side lighting and a small exhibit label add depth without inventing exhibits.
    for item in g['artifacts']:
        if not item['case']:continue
        x,y,base=item['x'],item['y'],item['base'];w,d,h=item['case']
        for side in [-1,1]:
            b.box('10_柜底窄金属包边',(x,y+side*d/2,base+.018),(w,.026,.025),brass,.003)
            b.box('10_柜顶嵌入灯槽',(x+side*(w/2-.045),y,base+h-.045),(.025,max(.2,d-.13),.018),luminous('10_暖白柜灯','#ffe7bd',1.1),.002)
        if item['id'] not in ['bells','chimes']:
            b.box('10_展品信息牌',(x-w*.27,y-d*.34,base+.06),(min(.26,w*.25),.12,.012),mat('10_信息牌暖灰','#c4bba5',0,.85),.002)
        light=spot(b.c,'10_展柜重点灯',(x,y-.12,base+h-.12),(x,y,base+.3),40,70)
        light.data.color=(1,.84,.64);light['web_intensity']=38.;light['web_shadow']=True
    w,d=g['size']
    # Warm wall light in each room, exported as punctual lights for the web viewer.
    for side in [-1,1]:
        light=spot(b.c,'10_展墙洗亮',(side*w*.28,d*.25,4.65),(side*w*.28,d*.48,2.6),90,90)
        light.data.color=(1,.86,.69);light['web_intensity']=28.;light['web_shadow']=False
    if slug=='zeng':
        limestone=surface('金声玉振米黄石墙','#b8a27a','marble',.65)
        b.box('10_金声玉振石墙',(0,8,2.5),(15,.22,5),limestone,.025)
        text(b,'金 声 玉 振',(0,7.85,3.6),.62,darkink)
    elif slug=='ancient':
        band=surface('古代展墙浅色腰带','#b8b291','stone',.83)
        for side in [-1,1]:b.box('10_侧墙米色腰带',(side*(w/2-.13),1,1.6),(.045,d-.8,.72),band,.006)
    elif slug=='modern':
        blue=surface('近代展板深蓝','#17517c','stone',.78)
        for o in s.objects:
            if o.name.startswith('蓝色竖向叙事板'):assign(o,blue)
    elif slug=='people':
        red=surface('英杰展朱红墙','#812c26','stone',.83)
        b.box('10_英杰展红色叙事墙',(-w/2+.14,1,2.5),(.05,d*.65,4.5),red,.008)
    for o in b.objects:
        o['gallery_id']=slug;o['part']='Gallery_'+slug
        o['accuracy']='photo-guided display furniture and lighting; positions and dimensions approximate'
        if o.type=='MESH' and not o.get('artifact_id'):project_uv(o,2)
    s.world.node_tree.nodes['Background'].inputs[1].default_value=.10
    s.view_settings.exposure=0
    finish(s,slug,ROOT/'models/galleries'/(slug+'.blend'))
    export_gallery(g)


def public(slug):
    print('POLISH_PUBLIC',slug,flush=True)
    bpy.ops.wm.open_mainfile(filepath=str(SOURCE/'public'/(slug+'.blend')),load_ui=False)
    s=bpy.context.scene;b=builder(s,slug)
    stone=surface('公共空间灰纹石材','#c1beb3','marble',.32)
    white=surface('公共空间白色石材','#e2e1d8','marble',.4)
    wood=surface('演奏厅红木','#69291f','wood',.57)
    fabric=surface('演奏厅暗红织物','#64201b','fabric',.96)
    for o in s.objects:
        if o.get('artifact_id'):continue
        if o.type=='MESH':
            name=o.name
            if any(k in name for k in ['地坪','地面','旋梯整块踏步','楼梯接层平台']):assign(o,stone,4)
            elif any(k in name for k in ['旋梯连续石材侧板','环廊','石材北墙']) and '玻璃' not in name:assign(o,white,5)
            elif name.startswith(('演奏厅红色侧墙','舞台')) and '背景' not in name:assign(o,wood,3)
            elif name.startswith(('软包座面','软包椅背')):
                assign(o,fabric,.4)
                for mod in o.modifiers:
                    if mod.type=='BEVEL':mod.segments=6;mod.harden_normals=True
                for p in o.data.polygons:p.use_smooth=True
                mod=o.modifiers.new('Soft upholstery normals','WEIGHTED_NORMAL');mod.keep_sharp=True
        if o.type=='LIGHT' and o.data.type=='AREA':o.data.specular_factor=.12
    if slug=='atrium':
        # Floor joints and low brass thresholds are based on the stone/metal material language.
        seam=mat('10_中庭石缝','#8e928a',0,.7)
        for x in range(-28,29,3):b.box('10_中庭纵向石缝',(x,0,.013),(.008,61,.006),seam,0)
        for y in range(-30,31,3):b.box('10_中庭横向石缝',(0,y,.014),(58,.008,.006),seam,0)
        # Keep the central tree columns white. Texture belongs on the surrounding stone surfaces.
        for o in s.objects:
            if o.type=='MESH' and o.name.startswith(('中庭北侧','旋梯连续')):assign(o,white,5)
        for x in [-22,22]:
            for y in [-16,18]:
                light=spot(b.c,'10_中庭暖色照明',(x,y,6.1),(x,y,0),90,95)
                light.data.color=(1,.92,.8);light['web_intensity']=70.;light['web_shadow']=False
        # A less upward-facing view includes the floor, stairs and material transitions.
        s.camera.location=(11,-26,3.1)
        s.camera.rotation_euler=(Vector((-5,7,9))-s.camera.location).to_track_quat('-Z','Y').to_euler()
    elif slug=='connection':
        s.world.node_tree.nodes['Background'].inputs[0].default_value=(.55,.69,.8,1)
        s.world.node_tree.nodes['Background'].inputs[1].default_value=.45
        for y in range(-18,19,2):b.box('10_廊道横向石缝',(0,y,.01),(12,.008,.004),mat('10_廊道接缝','#777b73',0,.8),0)
        for y in [-12,0,12]:
            light=spot(b.c,'10_连接廊顶灯',(0,y,5.1),(0,y,0),80,105)
            light.data.color=(1,.93,.84);light['web_intensity']=48.;light['web_shadow']=False
    else:
        for x in [-7,0,7]:
            light=spot(b.c,'10_舞台重点灯',(x,4,7.3),(x,8,2),170,65)
            light.data.color=(1,.82,.64);light['web_intensity']=180.;light['web_shadow']=True
        for y in [-9,-3,3]:
            light=spot(b.c,'10_观众区顶灯',(0,y,7),(0,y,.5),95,110)
            light.data.color=(1,.88,.73);light['web_intensity']=38.;light['web_shadow']=False
        for row in range(9):
            y=4-row*1.38;z=row*.16
            for x in [-.35,.35]:b.box('10_过道踏步灯',(x,y-.8,z+.12),(.09,.035,.035),luminous('10_过道暖光','#f1c992',.8),.003)
    for o in b.objects:o['part']='03_Atrium_Detail' if slug=='atrium' else 'Public_'+slug
    s.view_settings.exposure=-.25 if slug=='theatre' else -.3
    finish(s,slug,ROOT/'models/public'/(slug+'.blend'))
    if slug=='theatre':
        for o in list(s.objects):
            if o.get('artifact_id')=='bells-performance-copy':bpy.data.objects.remove(o,do_unlink=True)
        before=set(s.objects);bpy.ops.import_scene.gltf(filepath=str(ROOT/'models/artifacts/bells.glb'))
        for o in set(s.objects)-before:
            if not o.parent:o.location+=Vector((0,8,.9))
            o['artifact_id']='bells-performance-copy'
    optimize_export(list(s.objects),ROOT/'models/public'/(slug+'.glb'))


def campus():
    print('POLISH_CAMPUS',flush=True)
    bpy.ops.wm.open_mainfile(filepath=str(SOURCE/'hubei-museum.blend'),load_ui=False)
    s=bpy.context.scene
    # Work on the existing shell and landscape; public interiors and galleries are assembled later.
    for o in list(s.objects):
        part=str(o.get('part',''))
        if o.get('gallery_id') or o.get('artifact_id') or part.startswith(('03_','Public_')) or o.name.startswith('中庭玻璃顶'):
            bpy.data.objects.remove(o,do_unlink=True)
    b=builder(s,'campus')
    grass=surface('园区草地','#3f632f','grass',.96)
    paving=surface('广场灰色花岗岩','#b4b2a8','stone',.76)
    water=surface('湖水深青灰','#426c70','water',.2,.12)
    facade=surface('南馆浅灰石材','#dfded7','stone',.66)
    roof=surface('旧馆青灰瓦','#485664','stone',.78)
    wood=surface('旧馆檐下深木色','#49332a','wood',.62)
    for o in list(s.objects):
        if o.type!='MESH':continue
        if str(o.get('part','')).startswith('05_'):o['roof']=True
        if o.name.startswith(('园区阔叶树叶簇','不规则树枝','树干')):
            bpy.data.objects.remove(o,do_unlink=True);continue
        if o.name.startswith('园区地面'):assign(o,grass,30)
        elif o.name.startswith(('南广场','南侧台阶','广场分缝')):assign(o,paving,4)
        elif o.name.startswith('东侧湖面'):assign(o,water,13)
        elif any(k in o.name for k in ['石材立面','翼部屋顶','外墙','侧墙']):assign(o,facade,3)
        elif any(k in o.name for k in ['歇山屋顶','瓦垄','老馆屋脊']):assign(o,roof,2)
        elif any(k in o.name for k in ['檐下托梁','老馆出檐木构层']):assign(o,wood,2)
    seam=mat('10_室外石材细缝','#8d9288',0,.86)
    for y in range(-102,-39,4):b.box('10_广场横向铺地缝',(0,y,-7.487),(168,.016,.01),seam,0)
    for x in range(-82,83,4):b.box('10_广场纵向铺地缝',(x,-70,-7.486),(.016,64,.01),seam,0)
    # A connected park canopy is visible in the architect's aerial photograph. Locations remain approximate.
    bark=surface('乔木树皮','#534333','wood',.96)
    leaves=[mat('10_阔叶树冠'+str(i),c,0,.94) for i,c in enumerate(['#24472c','#355a31','#416b38','#54793d','#668044'])]
    rng=random.Random(102)
    points=[]
    for side in [-1,1]:
        for y in range(-104,172,11):points.append((side*rng.uniform(79,89),y+rng.uniform(-3,3)))
        for y in range(-98,170,16):points.append((side*rng.uniform(111,132),y+rng.uniform(-4,4)))
    for x in range(-118,130,13):points.append((x+rng.uniform(-4,4),166+rng.uniform(-3,4)))
    # The simplified east lake starts near x=95..110. Keep planting on its landward bank.
    points=[(x,y) for x,y in points if x<94]
    # No opaque low-poly balls: rounded, overlapping leaf sprays have real silhouette gaps.
    vs=[];fs=[];mis=[]
    for x,y in points:
        h=rng.uniform(8,12);z=-7.7
        b.tube('10_园林树干',[(x,y,z),(x+.15,y-.1,z+h*.55),(x,y,z+h*.85)],[.24,.17,.065],bark,8)
        for k in range(11):
            a=k*2.4;r=rng.uniform(1.1,3.6)
            end=Vector((x+math.cos(a)*r,y+math.sin(a)*r,z+h+rng.uniform(-2,1)))
            b.tube('10_园林细枝',[(x,y,z+h*.5),tuple(end)],.065,bark,6)
            for j in range(220):
                p=end+Vector((rng.gauss(0,1.25),rng.gauss(0,1.25),rng.gauss(0,.8)))
                theta=rng.random()*math.tau
                u=Vector((math.cos(theta),math.sin(theta),rng.uniform(-.5,.5)))*rng.uniform(.26,.48)
                v=Vector((-u.y,u.x,rng.uniform(-.08,.12)))*.7
                n=len(vs);vs.extend([tuple(p-u),tuple(p+v),tuple(p+u),tuple(p-v),tuple(p+Vector((0,0,.045)))])
                fs.extend([(n,n+1,n+4),(n+1,n+2,n+4),(n+2,n+3,n+4),(n+3,n,n+4)])
                mis.extend([rng.randrange(len(leaves))]*4)
    o=b.mesh('10_园林阔叶连续冠层',vs,fs,leaves[0],False)
    for m in leaves[1:]:o.data.materials.append(m)
    for p,i in zip(o.data.polygons,mis):p.material_index=i
    # Dark plinth reveal and facade panel joints retain the white building's articulation.
    for side in [-1,1]:
        cx=side*47.6
        for z in [10,12,14,16,18,20]:
            y=-32-(z-8)/12.4*3
            width=38+(z-8)/12.4*8
            for x in np.arange(-width/2+1.9,width/2,1.9):
                beam(b,'10_立面分格竖缝',(cx+x,y-.018,z-1.95),(cx+x,y-.018,z),.016,seam)
    for o in b.objects:o['part']='01_Campus';o['accuracy']='photo-guided material and landscape study; tree positions and species not surveyed'
    s.world.use_nodes=True
    bg=s.world.node_tree.nodes['Background'];bg.inputs[0].default_value=(.58,.72,.9,1);bg.inputs[1].default_value=.45
    for o in list(s.objects):
        if o.type=='LIGHT':bpy.data.objects.remove(o,do_unlink=True)
    data=bpy.data.lights.new('10_自然日光','SUN');data.energy=2.2;data.angle=math.radians(12)
    sun=bpy.data.objects.new('10_自然日光',data);s.collection.objects.link(sun);sun.rotation_euler=(math.radians(24),math.radians(-25),math.radians(-32))
    s.camera=bpy.data.objects['01_园区鸟瞰'];s.view_settings.exposure=-.25
    # Add the refined atrium in its original coordinates, including visible skylight and stairs.
    c=bpy.data.collections.new('10_IntegratedAtrium');s.collection.children.link(c)
    append_objects(ROOT/'models/public/atrium.blend',c)
    finish(s,'campus',ROOT/'models/campus-polished.blend')
    optimize_export(list(s.objects),ROOT/'models/museum-architecture.glb')
    print('CAMPUS_POLISHED',len(points),'trees',flush=True)


def assemble():
    bpy.ops.wm.open_mainfile(filepath=str(ROOT/'models/campus-polished.blend'),load_ui=False)
    s=bpy.context.scene
    for slug,offset in [('connection',(0,56,0)),('theatre',(-48,0,-6.8))]:
        c=bpy.data.collections.new('10_Public_'+slug);s.collection.children.link(c)
        append_objects(ROOT/'models/public'/(slug+'.blend'),c,offset)
    for g in GALLERIES:
        c=bpy.data.collections.new('10_Gallery_'+g['id']);s.collection.children.link(c)
        append_objects(ROOT/'models/galleries'/(g['id']+'.blend'),c,g['position'])
    s['version']='0.10';s['gallery_count']=11;s['artifact_count']=16
    s['scope']='11 permanent exhibition themes, representative artifacts and public spaces; approximate digital reconstruction'
    finish(s,'campus',ROOT/'models/hubei-museum.blend',render=False)


if __name__=='__main__':
    args=sys.argv[sys.argv.index('--')+1:] if '--' in sys.argv else []
    if not args:raise SystemExit('Choose galleries, public, campus, assemble or a gallery id')
    if 'galleries' in args:
        for g in GALLERIES:gallery(g)
    elif 'public' in args:
        for slug in ['atrium','connection','theatre']:public(slug)
    elif 'campus' in args:campus()
    elif 'assemble' in args:assemble()
    elif any(slug in args for slug in ['atrium','connection','theatre']):
        for slug in ['atrium','connection','theatre']:
            if slug in args:public(slug)
    else:
        for g in GALLERIES:
            if g['id'] in args:gallery(g)
    print('SPACE_POLISH_FINISHED',args,flush=True)
